### ISSUE TITLE
extreme instabilities on Debian 12 (bookworm)

### ISSUE THREAD

**Issue by zeph** [NVIDIA/nvkind#13]
works for us on `Ubuntu 22.04.4` but 

on Debian 12 (installing `bookworm-backports` for nvidia drivers) we have tons of Pods being
 killed completely randomly... having a hard time to isolate the issue if not just mentioning the
 OS we bootstrapped from (identical machine specs -> Hetzner's `GEX44`)

**Comment by zeph** [comment]
leaving on a single container, the system wont' stand a reboot, similar to https://github.com/kubernetes-sigs/kind/issues/2879#issuecomment-2472643645

 erroring on kube-api calls with `net/http: TLS handshake timeout`

**Comment by zeph** [comment]
![Image](https://github.com/user-attachments/assets/9ca49f21-7e1b-4099-8a98-726317c19932)
here's the status of a host after reboot... this is the applied configuration: 
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
{{- range $gpu := until numGPUs }}
- role: worker
  extraMounts:
    # We inject all NVIDIA GPUs using the nvidia-container-runtime.
    # This requires `accept-nvidia-visible-devices-as-volume-mounts = true` be set
    # in `/etc/nvidia-container-runtime/config.toml`
    - hostPath: /dev/null
      containerPath: /var/run/nvidia-container-devices/{{ $gpu }}
{{- end }}
```

**Comment by zeph** [comment]
logs are full of ` Normal   SandboxChanged  25m (x2 over 27m)      kubelet            Pod sandbox changed, it will be killed and re-created.` on the failing containers

**Comment by zeph** [comment]
suspecting this might be related https://github.com/canonical/microk8s/issues/2790#issuecomment-1421101259

**Comment by zeph** [comment]
it all leads here, to the `kicker` but this setting seems to get ignored... 
```yaml
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta1
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      advertise-address: "0.0.0.0"
```
