### ISSUE TITLE
Pod workload deployment step is throwing "executable file not found" error for nvidia-smi

### ISSUE THREAD

**Issue by aoyshi** [NVIDIA/nvkind#31]
I am able to follow all the steps in the readme and get the expected responses, until the very last pod workload step of:
```
cat << EOF | kubectl --context=kind-${KIND_CLUSTER_NAME} apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: ctr
    image: ubuntu:22.04
    command: ["nvidia-smi", "-L"]
    resources:
      limits:
        nvidia.com/gpu: 2
EOF
```

I get an error in the container (which never starts, so I cannot exec -it into into to investigate):
```
failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "nvidia-smi": executable file not found in $PATH: unknown.
```

I have the nvidia-device-plugin pods working correctly. Every step of the setup has worked so far until this very last one. Am I missing something?

**Comment by geraldstanje** [comment]
@aoyshi any update on this? did you fix it - if yes, how?

**Comment by aoyshi** [comment]
Yes I was able to resolve it. Here are the steps:

1. Configure `/etc/nvidia-container-runtime/config.toml` to have these two lines
```
accept-nvidia-visible-devices-envvar-when-unprivileged = false
accept-nvidia-visible-devices-as-volume-mounts = true
```

2. Restart your container service for the above changes to take effect:
```
sudo systemctl restart containerd
OR
sudo systemctl restart docker
```

3. Create cluster with 1 worker node that has access to all GPUs (in my case, I had 4) and any volume-mounted files:
```
export KIND_CLUSTER_NAME=example-cluster

./nvkind cluster create \
--name=${KIND_CLUSTER_NAME} \
--config-template=examples/explicit-gpus-per-worker.yaml \
--config-values=- \
<<EOF
workers:
- devices: [0,1,2,3]
EOF

kubectl label node "${KIND_CLUSTER_NAME}-worker"
  
./nvkind cluster print-gpus
```

4. Spin up k8s-device-plugin pods inside worker node:
```
helm repo add nvdp https://nvidia.github.io/k8s-device-plugin
helm repo update

helm upgrade -i \
  --kube-context=kind-${KIND_CLUSTER_NAME} \
  --namespace nvidia \
  --set gfd.enabled=true \
  --set runtimeClassName=nvidia \
  --set deviceListStrategy=volume-mounts \
  --set deviceDiscoveryStrategy=nvml \
  --create-namespace \
  nvidia-device-plugin nvdp/nvidia-device-plugin

kubectl --context=kind-${KIND_CLUSTER_NAME} get pod -n nvidia
kubectl --context=kind-${KIND_CLUSTER_NAME} get nodes -o json | jq -r '.items[] | select(.metadata.name | test("-worker[0-9]*$")) | {name: .metadata.name, "nvidia.com/gpu": .status.allocatable["nvidia.com/gpu"]}'
```

5. If you run `kubectl describe node example-cluster-worker` before and after spinning up k8-device-plugin pods, you will see that `nvidia.com/gpu` appears under 'Allocatable' after the device plugin pods are live.

6. Deploy a pod workload to the node. This will start up your custom docker container inside a pod, inside the node.

```
cat << EOF | kubectl --context=kind-${KIND_CLUSTER_NAME} apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  runtimeClassName: nvidia
  restartPolicy: OnFailure
  containers:
  - name: example-container
    image: your.docker.hub.repo.subdomain/your.docker.image.name:latest
    volumeMounts:
    - mountPath: /path/inside/container
      name: my-host-volume
    ports:
    - containerPort: 8000
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
    - name: ANY_ENV_ARGS_U_WANT
      value: "x=1"
    resources:
      limits:
        nvidia.com/gpu: 4
  volumes:
  - name: my-host-volume
    hostPath:
      path: /path/inside/node
      type: Directory
EOF

kubectl describe pod example-pod
kubectl logs example-pod -n default -c example-container
```

7. Forward the port so you can access the endpoint
`kubectl port-forward <pod-name> 8000:8000` and can reach at `curl -X GET http://localhost:8000/.....`

PS: This was the content of my `examples/explicit-gpus-per-worker.yaml` file that we get from the nvkind repo:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
{{- if hasKey $ "name" }}
name: {{ $.name }}
{{- end }}
nodes:
- role: control-plane
  extraLabels:
    nvidia.com/gpu.present: "true"
  {{- if hasKey $ "image" }}
  image: {{ $.image }}
  {{- end }}
{{- range $.workers }}
- role: worker
  extraLabels:
    nvidia.com/gpu.present: "true"
  {{- if hasKey $ "image" }}
  image: {{ $.image }}
  {{- end }}

  {{- if hasKey . "devices" }}
  {{- $devices := .devices }}
  {{- if not (kindIs "slice" $devices) }}
    {{- $devices = list .devices }}
  {{- end }}
  extraMounts:
    # We inject all NVIDIA GPUs using the nvidia-container-runtime.
    # This requires `accept-nvidia-visible-devices-as-volume-mounts = true` be set
    # in `/etc/nvidia-container-runtime/config.toml`
    {{- range $d := $devices }}
    - hostPath: /dev/null
      containerPath: /var/run/nvidia-container-devices/{{ $d }}
    {{- end }}
    - hostPath: /path/inside/host
      containerPath: /path/inside/node
  {{- end }}
{{- end }}
```
